version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.6.3
    working_directory: ~/german_numbers

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: run sorbet
          command: bundle exec srb tc --ignore vendor/
      - run:
          name: run rubocop
          command: bundle exec rubocop
      - run:
          name: run tests
          command: bundle exec rspec