name: Push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
    
    - name: Install deps
      run: bundle install
    
    - name: Run rubocop
      run: bundle exec rubocop
    
    - name: Run tests
      run: bundle exec rspec
